#!/usr/bin/env python3
"""Generate the repository architecture diagram with Mermaid CLI."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "outputs" / "figures" / "repository_architecture.png"


def build_mermaid() -> str:
    return """%% Generated by scripts/generate_architecture_diagram.py
%%{init: {"theme": "base", "themeVariables": {"fontFamily": "Inter, Arial, sans-serif", "primaryTextColor": "#243044", "lineColor": "#7c8da5"}, "flowchart": {"defaultRenderer": "elk", "htmlLabels": true, "curve": "basis", "nodeSpacing": 38, "rankSpacing": 74}}}%%
flowchart LR
    classDef repoBox fill:#fffaf5,stroke:#e9a46a,color:#243044,stroke-width:1.2px
    classDef prepBox fill:#ffffff,stroke:#75c6a3,color:#243044,stroke-width:1.2px
    classDef dataBox fill:#f5fbff,stroke:#6bb7df,color:#243044,stroke-width:1.2px
    classDef trainBox fill:#f8f5ff,stroke:#9a8be8,color:#243044,stroke-width:1.2px
    classDef annoBox fill:#f7fbf4,stroke:#83c98b,color:#243044,stroke-width:1.2px
    classDef evalBox fill:#fff9e8,stroke:#deb45a,color:#243044,stroke-width:1.2px
    classDef outputBox fill:#fff4c7,stroke:#c6921d,color:#243044,stroke-width:1.4px

    subgraph external["External inputs"]
        direction TB
        ext_culture["CultureLLM<br/><small>WVS Q&amp;A + cultural contexts<br/>(9 cultures, text only)</small>"]
        ext_percept["PerceptSent<br/><small>5,000 urban images</small>"]
        ext_agreement["multimodal LLMs see sentiment<br/><small>&sigma;<sub>3</sub>P<sub>5</sub> labels · 3,565 images</small>"]
        ext_annotation["MLLM Persona Evaluation<br/><small>LangGraph annotation pattern</small>"]
        ext_analysis["Analyzing Persona Effects MLLM<br/><small>analysis methodology</small>"]
    end

    subgraph stage1["Stage 1 — data preparation"]
        direction TB
        s1_wvs["WVS cultural anchoring<br/><small>cultural + baseline variants<br/>~2,100 examples per culture</small>"]
        s1_folds["Image folds<br/><small>stratified 5-fold CV<br/>used in Stage 4 evaluation</small>"]
    end

    subgraph stage2["Stage 2 — WVS fine-tuning (text only)"]
        direction TB
        s2_models["Model families<br/><small>Qwen3.5-2B · Gemma-4-E2B · Phi-4</small>"]
        s2_backend["Training backends<br/><small>MLX primary · HF/MPS fallback</small>"]
        s2_lora["Culture-specific LoRA adapters<br/><small>9 cultures · cultural + baseline<br/>no images · culture in weights</small>"]
        s2_mlflow["MLflow traces<br/><small>train/val loss · params</small>"]
    end

    subgraph stage3["Stage 3 — annotation"]
        direction TB
        s3_images["All 3,565 &sigma;<sub>3</sub>P<sub>5</sub> images"]
        s3_backend["Adapter inference<br/><small>Qwen/Gemma via MLX · Phi-4 via HF+MPS<br/>cultural/baseline LoRA from checkpoints/</small>"]
        s3_base["Base MLLM reference<br/><small>same neutral prompt · no LoRA adapter<br/>untrained inference-only condition</small>"]
        s3_graph["LangGraph pipeline<br/><small>image loader → assembler → annotator</small>"]
        s3_prompt["Neutral inference prompt<br/><small>culture baked into weights</small>"]
        s3_out["outputs/annotations/<br/><small>sentiment · caption · justification · tags<br/>(18 trained configs + 1 base reference) × 3 models</small>"]
    end

    subgraph stage4["Stage 4 — evaluation &amp; analysis"]
        direction TB
        s4_eval["Annotation evaluation<br/><small>accuracy · F1 · kappa vs &sigma;<sub>3</sub>P<sub>5</sub><br/>trained-vs-untrained · bootstrap CI · Holm-Bonferroni</small>"]
        s4_analysis["Cultural analysis<br/><small>Sentence-BERT similarity<br/>BERTopic · convergence metrics</small>"]
        s4_nb["Research notebooks<br/><small>EDA → convergence analysis</small>"]
        s4_out["Publication artifacts<br/><small>figures · LaTeX tables · reports</small>"]
    end

    ext_culture   --> s1_wvs
    ext_agreement --> s1_folds
    ext_annotation ~~~ s3_graph
    ext_analysis   ~~~ s4_analysis

    s1_wvs   --> s2_models
    s1_folds --> s4_eval

    s2_models  --> s2_backend --> s2_lora
    s2_backend --> s2_mlflow
    s2_lora    --> s3_backend

    ext_percept  --> s3_images
    s3_images    --> s3_graph
    s3_prompt    --> s3_backend
    s3_backend   --> s3_graph
    s3_base      --> s3_graph
    s3_graph     --> s3_out

    ext_agreement --> s4_eval
    s3_out --> s4_eval
    s3_out --> s4_analysis
    s4_eval     --> s4_out
    s4_analysis --> s4_nb --> s4_out

    class ext_culture,ext_percept,ext_agreement,ext_annotation,ext_analysis repoBox
    class s1_wvs,s1_folds prepBox
    class s2_models,s2_backend,s2_lora,s2_mlflow trainBox
    class s3_images,s3_backend,s3_base,s3_graph,s3_prompt annoBox
    class s3_out,s4_out outputBox
    class s4_eval,s4_analysis,s4_nb evalBox

    style external fill:#fff7ed,stroke:#f3b074,stroke-width:1.6px,color:#243044
    style stage1   fill:#ecfdf5,stroke:#79c7a2,stroke-width:1.6px,color:#243044
    style stage2   fill:#f5f3ff,stroke:#a69aef,stroke-width:1.6px,color:#243044
    style stage3   fill:#f0f9ff,stroke:#75bce3,stroke-width:1.6px,color:#243044
    style stage4   fill:#fffbeb,stroke:#e0b957,stroke-width:1.6px,color:#243044
"""


def renderer_command(renderer: str) -> list[str]:
    if renderer == "mmdc":
        mmdc = shutil.which("mmdc")
        if not mmdc:
            raise RuntimeError("Mermaid CLI executable 'mmdc' was not found on PATH.")
        return [mmdc]

    if renderer == "npx":
        npx = shutil.which("npx")
        if not npx:
            raise RuntimeError("npx was not found on PATH.")
        return [npx, "-y", "@mermaid-js/mermaid-cli"]

    mmdc = shutil.which("mmdc")
    if mmdc:
        return [mmdc]

    npx = shutil.which("npx")
    if npx:
        return [npx, "-y", "@mermaid-js/mermaid-cli"]

    raise RuntimeError(
        "No Mermaid renderer found. Install Mermaid CLI with "
        "`npm install -g @mermaid-js/mermaid-cli` or install Node/npm for npx."
    )


def render_png(
    *,
    mmd_path: Path,
    output_path: Path,
    renderer: str,
    background_color: str,
    width: int,
    scale: float,
    theme: str | None,
) -> None:
    command = [
        *renderer_command(renderer),
        "--input",
        str(mmd_path),
        "--output",
        str(output_path),
        "--backgroundColor",
        background_color,
        "--width",
        str(width),
        "--scale",
        str(scale),
    ]
    if theme:
        command.extend(["--theme", theme])
    subprocess.run(command, cwd=REPO_ROOT, check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a horizontal Mermaid architecture diagram and export it as PNG."
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"PNG output path. Default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)}",
    )
    parser.add_argument(
        "--mmd-output",
        type=Path,
        default=None,
        help="Mermaid source output path. Default: same as PNG with .mmd extension.",
    )
    parser.add_argument(
        "--renderer",
        choices=("auto", "mmdc", "npx"),
        default="auto",
        help="Renderer to use. Default: auto.",
    )
    parser.add_argument(
        "--background-color",
        default="white",
        help="PNG background color passed to Mermaid CLI. Default: white.",
    )
    parser.add_argument(
        "--width",
        type=int,
        default=10000,
        help="Render viewport width in pixels. Default: 10000.",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="PNG scale factor. Default: 1.0.",
    )
    parser.add_argument(
        "--theme",
        choices=("default", "forest", "dark", "neutral"),
        default=None,
        help="Optional Mermaid CLI theme override. By default, styling comes from the .mmd init block.",
    )
    parser.add_argument(
        "--skip-render",
        action="store_true",
        help="Only write the Mermaid .mmd file; do not export PNG.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output.is_absolute() else REPO_ROOT / args.output
    mmd_path = args.mmd_output or output_path.with_suffix(".mmd")
    mmd_path = mmd_path if mmd_path.is_absolute() else REPO_ROOT / mmd_path

    output_path.parent.mkdir(parents=True, exist_ok=True)
    mmd_path.parent.mkdir(parents=True, exist_ok=True)
    mmd_path.write_text(build_mermaid(), encoding="utf-8")

    print(f"Wrote Mermaid source: {mmd_path.relative_to(REPO_ROOT)}")

    if args.skip_render:
        print("Skipped PNG rendering.")
        return 0

    try:
        render_png(
            mmd_path=mmd_path,
            output_path=output_path,
            renderer=args.renderer,
            background_color=args.background_color,
            width=args.width,
            scale=args.scale,
            theme=args.theme,
        )
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"Failed to render PNG: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote PNG diagram: {output_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
